Repository Summer-Bootcamp-2024/SML, pull requests merged in 2024-07, with the labels that each got.

#14 Chore/#13
  docker-compose.yml
  nginx/Dockerfile
  nginx/nginx.conf
Labels: 환경설정

#17 [#16] Chore: docker-compose.yml 수정
  docker-compose.yml
Labels: 환경설정

#21 [#20] Feat: 프로메테우스, 그라파나 추가
  .gitignore
  docker-compose.yml
  grafana/data/grafana.db
  prometheus/prometheus.yml
Labels: 기능구현

#28 [#27]Bug: platform: linux/amd 코드 추가
  docker-compose.yml
Labels: 오류수정

#32 [#31] Bug: docker-compose logstash 수정
  docker-compose.yml
Labels: 오류수정

#36 Chore/#35
  .gitignore
  docker-compose-prod.yml
  docker-compose.yml
Labels: 환경설정

#39 [chore] frontend docker-compose.yml 추가
  docker-compose.yml
Labels: 환경설정

#42 Chore/#41 nginx에서 정적파일 serving하도록 연동
  docker-compose-prod.yml
  docker-compose.yml
  nginx/nginx.conf
Labels: 환경설정

#45 [#44] Refector: docker-compose.yml, prod.yml 파일 logstash, filebeat 주석처리
  docker-compose-prod.yml
  docker-compose.yml
Labels: 리팩토링

#47 [#46] Chore: nginx.conf 수정
  nginx/nginx.conf
Labels: 환경설정

#49 [#48] Refactor: ci/cd코드 수정
  .github/workflows/cd.yml
Labels: 리팩토링

#51 [#50] Refactor: ci 코드 수정
  .github/workflows/ci.yml
Labels: 리팩토링

#53 [#52] Refactor: CD 코드 수정
  .github/workflows/cd.yml
Labels: 리팩토링

#55 [#54] Chore: docker-compose-prod.yml 수정
  docker-compose-prod.yml
Labels: 오류수정, 환경설정
